// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC560gBo4et1h8PDHcn3LqPqvacP5QBzRY',
    appId: '1:459306496225:web:10add6910ba59f30bf87a0',
    messagingSenderId: '459306496225',
    projectId: 'it303todolistapp',
    authDomain: 'it303todolistapp.firebaseapp.com',
    storageBucket: 'it303todolistapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD85K0sVn3JW91SOWS602N0UXmdoSH63YQ',
    appId: '1:459306496225:android:77cf76e6cec2e577bf87a0',
    messagingSenderId: '459306496225',
    projectId: 'it303todolistapp',
    storageBucket: 'it303todolistapp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAToN54W7qh6ux47cXLMXQoC-VMjX8wV6o',
    appId: '1:459306496225:web:2dd3737b1af0bc4ebf87a0',
    messagingSenderId: '459306496225',
    projectId: 'it303todolistapp',
    authDomain: 'it303todolistapp.firebaseapp.com',
    storageBucket: 'it303todolistapp.firebasestorage.app',
  );
}
